/* GENERATED by scripts/build-manifest.mjs — do not hand-edit.
   Regenerate after adding, renaming, or editing a resume:
     node scripts/build-manifest.mjs
*/

window.RESUME_LIBRARY = [
  {
    "slug": "master",
    "label": "Master (all experience)",
    "data": {
      "fileName": "Pratik_Patil_Product_Designer_Resume",
      "name": "Pratik Patil",
      "title": "Product Designer | UX Designer",
      "tagline": "4+ Years · B2B SaaS · Enterprise · Healthcare · Complex Workflows",
      "links": [
        {
          "label": "prateekdesigns.framer.website",
          "href": "https://prateekdesigns.framer.website"
        },
        {
          "label": "LinkedIn",
          "href": "https://www.linkedin.com/in/uiuxpratik"
        },
        {
          "label": "Behance",
          "href": "https://www.behance.net/uiuxpratik"
        }
      ],
      "contact": [
        {
          "label": "Phone",
          "value": "992-135-4164",
          "href": "tel:+919921354164"
        },
        {
          "label": "Email",
          "value": "uiuxpratik@gmail.com",
          "href": "mailto:uiuxpratik@gmail.com"
        },
        {
          "label": "Location",
          "value": "Bangalore, India"
        }
      ],
      "summary": "Product Designer with 4+ years of experience designing complex B2B, SaaS, and enterprise products across healthcare and IT domains. Experienced in user research, problem discovery, workflow design, interaction design, prototyping, usability testing, and design systems. Worked closely with product managers and engineers to translate complex user and business requirements into clearer, scalable product experiences, with experience contributing to measurable improvements in issue resolution and product conversion.",
      "experience": [
        {
          "company": "Global Software Resource",
          "role": "UX Designer",
          "client": "Client: Siemens Healthineers",
          "dates": "May 2024 — Present",
          "bullets": [
            "Designed user experiences for an **enterprise troubleshooting platform used by medical technicians at Siemens Healthineers**, translating complex diagnostic workflows and stakeholder requirements into clearer product experiences.",
            "Contributed to an **AI-assisted support platform handling 300–400 diagnostic tickets per day**, working across research, interaction design, and product delivery for the Siemens Healthineers project.",
            "Conducted **user interviews and usability testing** to identify workflow issues and improve clarity, contributing to an estimated **~30% faster issue resolution**.",
            "Collaborated with **product managers, requirement engineers, and developers** to translate requirements into UX solutions and support iterative product delivery.",
            "Worked within agile teams to refine workflows, communicate design decisions, and support feature delivery from design through development."
          ]
        },
        {
          "company": "BETSOL",
          "role": "UX Designer",
          "dates": "June 2022 — April 2024",
          "bullets": [
            "Designed UX for an **enterprise backup and monitoring product used by IT administrators**, working across complex product workflows and administrative experiences.",
            "Contributed to improvements in key product flows that supported **~40%+ higher trial-to-paid conversion**.",
            "Redesigned onboarding and core workflows to **reduce setup complexity and improve usability** for enterprise users.",
            "Built and maintained **reusable design components**, improving consistency across product experiences and supporting efficient design-to-development handoff.",
            "Collaborated within agile delivery teams, working with product and engineering stakeholders through design iteration, feedback, and implementation."
          ]
        },
        {
          "company": "HIE-HQ",
          "role": "UX Trainee",
          "dates": "January 2022 — May 2022",
          "bullets": [
            "Supported research, wireframing, and prototyping across multiple client projects.",
            "Assisted in creating internal **design systems and shared design tools** used by designers.",
            "Participated in design reviews and feedback sessions to improve design quality and communication.",
            "Developed foundational experience in UX research, interaction design, collaboration, and design execution."
          ]
        }
      ],
      "education": [
        {
          "school": "Mumbai University",
          "dates": "2022",
          "degree": "Bachelor of Engineering — Computer Engineering"
        }
      ],
      "skills": [
        {
          "group": "Product & UX Design",
          "items": "Product Design, User Research, Problem Discovery, Interaction Design, Information Architecture, User Flows, Journey Mapping, Usability Testing, Wireframing, Prototyping"
        },
        {
          "group": "Product & Collaboration",
          "items": "Problem Framing, Design Critique, Stakeholder Collaboration, Cross-functional Collaboration, Design Storytelling, Feedback & Iteration, Agile/Scrum, Design-to-Development Handoff"
        },
        {
          "group": "Design Systems & Quality",
          "items": "Design Systems, Component Design, Accessibility, WCAG 2.1 AA, Visual Design, Interaction Design, Responsive Design"
        }
      ],
      "tools": "Figma, FigJam, Miro, Adobe Illustrator, Photoshop, Claude, Lovable",
      "recognition": [
        "Best Performing Employee — Siemens Healthineers",
        "Top 10% UX Designer — Upwork"
      ]
    }
  },
  {
    "slug": "motorola-solutions",
    "label": "Motorola Solutions — Senior UX Designer",
    "data": {
      "fileName": "Pratik_Patil_UX_Designer_Resume_Motorola",
      "name": "Pratik Patil",
      "title": "Product Designer | UX Designer",
      "tagline": "4+ Years · User Research · Interaction Design · B2B SaaS · Enterprise · Healthcare",
      "links": [
        {
          "label": "prateekdesigns.framer.website",
          "href": "https://prateekdesigns.framer.website"
        },
        {
          "label": "LinkedIn",
          "href": "https://www.linkedin.com/in/uiuxpratik"
        },
        {
          "label": "Behance",
          "href": "https://www.behance.net/uiuxpratik"
        }
      ],
      "contact": [
        {
          "label": "Phone",
          "value": "992-135-4164",
          "href": "tel:+919921354164"
        },
        {
          "label": "Email",
          "value": "uiuxpratik@gmail.com",
          "href": "mailto:uiuxpratik@gmail.com"
        },
        {
          "label": "Location",
          "value": "Bangalore, India"
        }
      ],
      "summary": "Product/UX Designer with 4+ years of experience designing complex B2B, SaaS, and enterprise products across healthcare and IT domains. Grounded in user research and usability testing, translating ambiguous technical and business requirements into clear interaction models and prototypes. Partner directly with product managers, requirement engineers, and developers within agile teams, communicating design decisions and iterating from insight through to shipped, measurable outcomes.",
      "experience": [
        {
          "company": "Global Software Resource",
          "role": "UX Designer",
          "client": "Client: Siemens Healthineers",
          "dates": "May 2024 — Present",
          "bullets": [
            "Conducted **user interviews and usability testing** to identify workflow issues on an enterprise troubleshooting platform, contributing to an estimated **~30% faster issue resolution**.",
            "Designed user experiences for an **enterprise troubleshooting platform used by medical technicians at Siemens Healthineers**, translating complex diagnostic workflows and stakeholder requirements into clearer product experiences.",
            "Contributed to an **AI-assisted support platform handling 300–400 diagnostic tickets per day**, working across research, interaction design, and product delivery for the Siemens Healthineers project.",
            "Collaborated with **product managers, requirement engineers, and developers** to translate requirements into UX solutions and support iterative product delivery.",
            "Worked within agile teams to refine workflows, communicate design decisions, and support feature delivery from design through development."
          ]
        },
        {
          "company": "BETSOL",
          "role": "UX Designer",
          "dates": "June 2022 — April 2024",
          "bullets": [
            "Designed UX for an **enterprise backup and monitoring product used by IT administrators**, working across complex product workflows and administrative experiences.",
            "Redesigned onboarding and core workflows to **reduce setup complexity and improve usability** for enterprise users, based on observed user friction.",
            "Contributed to improvements in key product flows that supported **~40%+ higher trial-to-paid conversion**.",
            "Built and maintained **reusable design components**, improving consistency across product experiences and supporting efficient design-to-development handoff.",
            "Collaborated within agile delivery teams, working with product and engineering stakeholders through design iteration, feedback, and implementation."
          ]
        },
        {
          "company": "HIE-HQ",
          "role": "UX Trainee",
          "dates": "January 2022 — May 2022",
          "bullets": [
            "Supported research, wireframing, and prototyping across multiple client projects.",
            "Assisted in creating internal **design systems and shared design tools** used by designers.",
            "Participated in design reviews and feedback sessions to improve design quality and communication.",
            "Developed foundational experience in UX research, interaction design, collaboration, and design execution."
          ]
        }
      ],
      "education": [
        {
          "school": "Mumbai University",
          "dates": "2022",
          "degree": "Bachelor of Engineering — Computer Engineering"
        }
      ],
      "skills": [
        {
          "group": "Design & Research",
          "items": "User Research, User Interviews, Usability Testing, Interaction Design, Problem Discovery, Information Architecture, User Flows, Journey Mapping, Wireframing, Prototyping"
        },
        {
          "group": "Collaboration & Communication",
          "items": "Design Storytelling, Stakeholder Collaboration, Cross-functional Collaboration, Design Critique, Feedback & Iteration, Agile/Scrum"
        },
        {
          "group": "Design Systems & Quality",
          "items": "Design Systems, Component Design, Accessibility, WCAG 2.1 AA, Visual Design, Responsive Design"
        }
      ],
      "tools": "Figma, FigJam, Miro, Adobe Illustrator, Photoshop, Claude, Lovable",
      "recognition": [
        "Best Performing Employee — Siemens Healthineers",
        "Top 10% UX Designer — Upwork"
      ]
    }
  }
];
